
# get the variable list
custom_vars = ['wh_mva :=  WHmva()',
               'wh_ptV :=  WHptV()'
                ]


diphoton_variables = ["mass            := diPhoton.mass",
                      "diphoton_pt     := diPhoton.pt",
                      "diphoton_mva    := diPhotonMVA.result",
                      "pho1_pt         := diPhoton.leadingPhoton.pt",
                      "pho1_eta        := diPhoton.leadingPhoton.eta",
                      "pho1_phi        := diPhoton.leadingPhoton.phi",
                      "pho1_energy     := diPhoton.leadingPhoton.energy",
                      "pho1_full5x5_r9 := diPhoton.leadingPhoton.full5x5_r9",
                      "pho1_idmva      := diPhoton.leadPhotonId",
                      "pho1_genMatchType:=diPhoton.leadingPhoton.genMatchType",
                      "pho2_pt         := diPhoton.subLeadingPhoton.pt",
                      "pho2_eta        := diPhoton.subLeadingPhoton.eta",
                      "pho2_phi        := diPhoton.subLeadingPhoton.phi",
                      "pho2_energy     := diPhoton.subLeadingPhoton.energy",
                      "pho2_full5x5_r9 := diPhoton.subLeadingPhoton.full5x5_r9",
                      "pho2_idmva      := diPhoton.subLeadPhotonId",
                      "pho2_genMatchType:=diPhoton.subLeadingPhoton.genMatchType",
                      "pho1_ptOverMgg  := diPhoton.leadingPhoton.pt/diPhoton.mass",
                      "pho2_ptOverMgg  := diPhoton.subLeadingPhoton.pt/diPhoton.mass",
                      ]


leptons_variables = [ "mu1_pt         :=  ? muons.size()>0 ? muons[0].pt() : -100 ",
                      "mu1_phi        :=  ? muons.size()>0 ? muons[0].phi() : -100 ",
                      "mu1_eta        :=  ? muons.size()>0 ? muons[0].eta() : -100 ",
                      "mu1_energy     :=  ? muons.size()>0 ? muons[0].energy() : -100 ",
                      "mu2_pt         :=  ? muons.size()>1 ? muons[1].pt() : -100 ",
                      "mu2_phi        :=  ? muons.size()>1 ? muons[1].phi() : -100 ",
                      "mu2_eta        :=  ? muons.size()>1 ? muons[1].eta() : -100 ",
                      "mu2_energy     :=  ? muons.size()>1 ? muons[1].energy() : -100 ",
                      "ele1_pt        :=  ? electrons.size()>0 ? electrons[0].pt() : -100 ",
                      "ele1_phi       :=  ? electrons.size()>0 ? electrons[0].phi() : -100 ",
                      "ele1_eta       :=  ? electrons.size()>0 ? electrons[0].eta() : -100 ",
                      "ele1_energy    :=  ? electrons.size()>0 ? electrons[0].energy() : -100 ",
                      "ele2_pt        :=  ? electrons.size()>1 ? electrons[1].pt() : -100 ",
                      "ele2_phi       :=  ? electrons.size()>1 ? electrons[1].phi() : -100 ",
                      "ele2_eta       :=  ? electrons.size()>1 ? electrons[1].eta() : -100 ",
                      "ele2_energy    :=  ? electrons.size()>1 ? electrons[1].energy() : -100 ",
                      "nMuons         :=  muons.size()",
                      "nEle           :=  electrons.size()"
                     ]

jets_variables = ["njets := jets.size()",
                  "jet1_pt     :=  ? jets.size()>0 ? jets[0].pt : -100 ",
                  "jet1_phi    :=  ? jets.size()>0 ? jets[0].phi : -100 ",
                  "jet1_eta    :=  ? jets.size()>0 ? jets[0].eta : -100 ",
                  "jet1_energy :=  ? jets.size()>0 ? jets[0].energy : -100 ",
                  "jet2_pt     :=  ? jets.size()>1 ? jets[1].pt : -100 ",
                  "jet2_phi    :=  ? jets.size()>1 ? jets[1].phi : -100 ",
                  "jet2_eta    :=  ? jets.size()>1 ? jets[1].eta : -100 ",
                  "jet2_energy :=  ? jets.size()>1 ? jets[1].energy : -100 ",
                  "jet3_pt     :=  ? jets.size()>2 ? jets[2].pt : -100 ",
                  "jet3_phi    :=  ? jets.size()>2 ? jets[2].phi : -100 ",
                  "jet3_eta    :=  ? jets.size()>2 ? jets[2].eta : -100 ",
                  "jet3_energy :=  ? jets.size()>2 ? jets[2].energy : -100 ",
                  "jet4_pt     :=  ? jets.size()>3 ? jets[3].pt : -100 ",
                  "jet4_phi    :=  ? jets.size()>3 ? jets[3].phi : -100 ",
                  "jet4_eta    :=  ? jets.size()>3 ? jets[3].eta : -100 ",
                  "jet4_energy :=  ? jets.size()>3 ? jets[3].energy : -100 ",
                  "jet5_pt     :=  ? jets.size()>4 ? jets[4].pt : -100 ",
                  "jet5_phi    :=  ? jets.size()>4 ? jets[4].phi : -100 ",
                  "jet5_eta    :=  ? jets.size()>4 ? jets[4].eta : -100 ",
                  "jet5_energy :=  ? jets.size()>4 ? jets[4].energy : -100 ",
                  "jet6_pt     :=  ? jets.size()>5 ? jets[5].pt : -100 ",
                  "jet6_phi    :=  ? jets.size()>5 ? jets[5].phi : -100 ",
                  "jet6_eta    :=  ? jets.size()>5 ? jets[5].eta : -100 ",
                  "jet6_energy :=  ? jets.size()>5 ? jets[5].energy : -100 ",
                  "jet7_pt     :=  ? jets.size()>6 ? jets[6].pt : -100 ",
                  "jet7_phi    :=  ? jets.size()>6 ? jets[6].phi : -100 ",
                  "jet7_eta    :=  ? jets.size()>6 ? jets[6].eta : -100 ",
                  "jet7_energy :=  ? jets.size()>6 ? jets[6].energy : -100 "
                  ]

met_variables = ["met_pt  := met.corPt()",
                 "met_phi := met.corPhi()"]


gen_variables = ["hasZ := tagTruth().associatedZ",
                 "hasW := tagTruth().associatedW",
                 "VhasL := tagTruth().VhasLeptons",
                 "VhasNu := tagTruth().VhasNeutrinos",
                 "VhasQ := tagTruth().VhasHadrons"
                 ]

#dR_variables_WHLeptonic = [ "dR_Pho1Jet1_wh :=  ? jets.size() > 0 ? whleptonictags_obj.deltaRPho1Jet1 : -100"
dR_variables_WHLeptonic = ["dR_Pho1Jet1_wh :=  ? jets.size() > 0 ? deltaR(jets[0].eta, jets[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho1Jet2_wh :=  ? jets.size() > 1 ? deltaR(jets[1].eta, jets[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",  
                           "dR_Pho2Jet1_wh :=  ? jets.size() > 0 ? deltaR(jets[0].eta, jets[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho2Jet2_wh :=  ? jets.size() > 1 ? deltaR(jets[1].eta, jets[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Ele1_wh :=  ? electrons.size() > 0 ? deltaR(electrons[0].eta, electrons[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho1Ele2_wh :=  ? electrons.size() > 1 ? deltaR(electrons[1].eta, electrons[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",                           
                           "dR_Pho2Ele1_wh :=  ? electrons.size() > 0 ? deltaR(electrons[0].eta, electrons[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",                          
                           "dR_Pho2Ele2_wh :=  ? electrons.size() > 1 ? deltaR(electrons[1].eta, electrons[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Ele3_wh :=  ? electrons.size() > 2 ? deltaR(electrons[2].eta, electrons[2].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Ele3_wh :=  ? electrons.size() > 2 ? deltaR(electrons[2].eta, electrons[2].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",                          
                           "dR_Pho1Ele4_wh :=  ? electrons.size() > 3 ? deltaR(electrons[3].eta, electrons[3].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Ele4_wh :=  ? electrons.size() > 3 ? deltaR(electrons[3].eta, electrons[3].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",                          
                           "dR_Pho1Ele5_wh :=  ? electrons.size() > 4 ? deltaR(electrons[4].eta, electrons[4].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Ele5_wh :=  ? electrons.size() > 4 ? deltaR(electrons[4].eta, electrons[4].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",                          
                           "dR_Pho1Mu1_wh  :=  ? muons.size() > 0 ? deltaR(muons[0].eta, muons[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho1Mu2_wh  :=  ? muons.size() > 1 ? deltaR(muons[1].eta, muons[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Mu1_wh  :=  ? muons.size() > 0 ? deltaR(muons[0].eta, muons[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho2Mu2_wh  :=  ? muons.size() > 1 ? deltaR(muons[1].eta, muons[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Mu1Jet1_wh  :=  ? (muons.size() > 0 && jets.size() > 0) ? deltaR(muons[0].eta, muons[0].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu1Jet2_wh  :=  ? (muons.size() > 0 && jets.size() > 1) ? deltaR(muons[0].eta, muons[0].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Mu2Jet1_wh  :=  ? (muons.size() > 1 && jets.size() > 0) ? deltaR(muons[1].eta, muons[1].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu2Jet2_wh  :=  ? (muons.size() > 1 && jets.size() > 1) ? deltaR(muons[1].eta, muons[1].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Mu1Jet3_wh  :=  ? (muons.size() > 0 && jets.size() > 2) ? deltaR(muons[0].eta, muons[0].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Mu2Jet3_wh  :=  ? (muons.size() > 1 && jets.size() > 2) ? deltaR(muons[1].eta, muons[1].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Mu1Jet4_wh  :=  ? (muons.size() > 0 && jets.size() > 3) ? deltaR(muons[0].eta, muons[0].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Mu2Jet4_wh  :=  ? (muons.size() > 1 && jets.size() > 3) ? deltaR(muons[1].eta, muons[1].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Mu1Jet5_wh  :=  ? (muons.size() > 0 && jets.size() > 4) ? deltaR(muons[0].eta, muons[0].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Mu2Jet5_wh  :=  ? (muons.size() > 1 && jets.size() > 4) ? deltaR(muons[1].eta, muons[1].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Mu1Jet6_wh  :=  ? (muons.size() > 0 && jets.size() > 5) ? deltaR(muons[0].eta, muons[0].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Mu2Jet6_wh  :=  ? (muons.size() > 1 && jets.size() > 5) ? deltaR(muons[1].eta, muons[1].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Mu1Jet7_wh  :=  ? (muons.size() > 0 && jets.size() > 6) ? deltaR(muons[0].eta, muons[0].phi, jets[6].eta, jets[6].phi) : -100 ",
                           "dR_Mu2Jet7_wh  :=  ? (muons.size() > 1 && jets.size() > 6) ? deltaR(muons[1].eta, muons[1].phi, jets[6].eta, jets[6].phi) : -100 ",
                           "dR_Mu3Jet1_wh  :=  ? (muons.size() > 2 && jets.size() > 0) ? deltaR(muons[2].eta, muons[2].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu3Jet2_wh  :=  ? (muons.size() > 2 && jets.size() > 1) ? deltaR(muons[2].eta, muons[2].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Mu3Jet3_wh  :=  ? (muons.size() > 2 && jets.size() > 2) ? deltaR(muons[2].eta, muons[2].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Mu3Jet4_wh  :=  ? (muons.size() > 2 && jets.size() > 3) ? deltaR(muons[2].eta, muons[2].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Mu3Jet5_wh  :=  ? (muons.size() > 2 && jets.size() > 4) ? deltaR(muons[2].eta, muons[2].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Mu3Jet6_wh  :=  ? (muons.size() > 2 && jets.size() > 5) ? deltaR(muons[2].eta, muons[2].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Mu3Jet7_wh  :=  ? (muons.size() > 2 && jets.size() > 6) ? deltaR(muons[2].eta, muons[2].phi, jets[6].eta, jets[6].phi) : -100 ",  
                           "dR_Mu4Jet1_wh  :=  ? (muons.size() > 3 && jets.size() > 0) ? deltaR(muons[3].eta, muons[3].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu4Jet2_wh  :=  ? (muons.size() > 3 && jets.size() > 1) ? deltaR(muons[3].eta, muons[3].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Mu4Jet3_wh  :=  ? (muons.size() > 3 && jets.size() > 2) ? deltaR(muons[3].eta, muons[3].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Mu4Jet4_wh  :=  ? (muons.size() > 3 && jets.size() > 3) ? deltaR(muons[3].eta, muons[3].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Mu4Jet5_wh  :=  ? (muons.size() > 3 && jets.size() > 4) ? deltaR(muons[3].eta, muons[3].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Mu4Jet6_wh  :=  ? (muons.size() > 3 && jets.size() > 5) ? deltaR(muons[3].eta, muons[3].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Mu4Jet7_wh  :=  ? (muons.size() > 3 && jets.size() > 6) ? deltaR(muons[3].eta, muons[3].phi, jets[6].eta, jets[6].phi) : -100 ",  
                           "dR_Mu5Jet1_wh  :=  ? (muons.size() > 4 && jets.size() > 0) ? deltaR(muons[4].eta, muons[4].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu5Jet2_wh  :=  ? (muons.size() > 4 && jets.size() > 1) ? deltaR(muons[4].eta, muons[4].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Mu5Jet3_wh  :=  ? (muons.size() > 4 && jets.size() > 2) ? deltaR(muons[4].eta, muons[4].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Mu5Jet4_wh  :=  ? (muons.size() > 4 && jets.size() > 3) ? deltaR(muons[4].eta, muons[4].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Mu5Jet5_wh  :=  ? (muons.size() > 4 && jets.size() > 4) ? deltaR(muons[4].eta, muons[4].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Mu5Jet6_wh  :=  ? (muons.size() > 4 && jets.size() > 5) ? deltaR(muons[4].eta, muons[4].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Mu5Jet7_wh  :=  ? (muons.size() > 4 && jets.size() > 6) ? deltaR(muons[4].eta, muons[4].phi, jets[6].eta, jets[6].phi) : -100 ", 
                           "dR_Ele1Jet1_wh  :=  ? (electrons.size() > 0 && jets.size() > 0) ? deltaR(electrons[0].eta, electrons[0].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele1Jet2_wh  :=  ? (electrons.size() > 0 && jets.size() > 1) ? deltaR(electrons[0].eta, electrons[0].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele2Jet1_wh  :=  ? (electrons.size() > 1 && jets.size() > 0) ? deltaR(electrons[1].eta, electrons[1].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele2Jet2_wh  :=  ? (electrons.size() > 1 && jets.size() > 1) ? deltaR(electrons[1].eta, electrons[1].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele1Jet3_wh  :=  ? (electrons.size() > 0 && jets.size() > 2) ? deltaR(electrons[0].eta, electrons[0].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Ele2Jet3_wh  :=  ? (electrons.size() > 1 && jets.size() > 2) ? deltaR(electrons[1].eta, electrons[1].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Ele1Jet4_wh  :=  ? (electrons.size() > 0 && jets.size() > 3) ? deltaR(electrons[0].eta, electrons[0].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Ele2Jet4_wh  :=  ? (electrons.size() > 1 && jets.size() > 3) ? deltaR(electrons[1].eta, electrons[1].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Ele1Jet5_wh  :=  ? (electrons.size() > 0 && jets.size() > 4) ? deltaR(electrons[0].eta, electrons[0].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Ele2Jet5_wh  :=  ? (electrons.size() > 1 && jets.size() > 4) ? deltaR(electrons[1].eta, electrons[1].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Ele1Jet6_wh  :=  ? (electrons.size() > 0 && jets.size() > 5) ? deltaR(electrons[0].eta, electrons[0].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Ele2Jet6_wh  :=  ? (electrons.size() > 1 && jets.size() > 5) ? deltaR(electrons[1].eta, electrons[1].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Ele1Jet7_wh  :=  ? (electrons.size() > 0 && jets.size() > 6) ? deltaR(electrons[0].eta, electrons[0].phi, jets[6].eta, jets[6].phi) : -100 ",
                           "dR_Ele2Jet7_wh  :=  ? (electrons.size() > 1 && jets.size() > 6) ? deltaR(electrons[1].eta, electrons[1].phi, jets[6].eta, jets[6].phi) : -100 ",
                           "dR_Ele3Jet1_wh  :=  ? (electrons.size() > 2 && jets.size() > 0) ? deltaR(electrons[2].eta, electrons[2].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele3Jet2_wh  :=  ? (electrons.size() > 2 && jets.size() > 1) ? deltaR(electrons[2].eta, electrons[2].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele3Jet3_wh  :=  ? (electrons.size() > 2 && jets.size() > 2) ? deltaR(electrons[2].eta, electrons[2].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Ele3Jet4_wh  :=  ? (electrons.size() > 2 && jets.size() > 3) ? deltaR(electrons[2].eta, electrons[2].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Ele3Jet5_wh  :=  ? (electrons.size() > 2 && jets.size() > 4) ? deltaR(electrons[2].eta, electrons[2].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Ele3Jet6_wh  :=  ? (electrons.size() > 2 && jets.size() > 5) ? deltaR(electrons[2].eta, electrons[2].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Ele3Jet7_wh  :=  ? (electrons.size() > 2 && jets.size() > 6) ? deltaR(electrons[2].eta, electrons[2].phi, jets[6].eta, jets[6].phi) : -100 ",  
                           "dR_Ele4Jet1_wh  :=  ? (electrons.size() > 3 && jets.size() > 0) ? deltaR(electrons[3].eta, electrons[3].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele4Jet2_wh  :=  ? (electrons.size() > 3 && jets.size() > 1) ? deltaR(electrons[3].eta, electrons[3].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele4Jet3_wh  :=  ? (electrons.size() > 3 && jets.size() > 2) ? deltaR(electrons[3].eta, electrons[3].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Ele4Jet4_wh  :=  ? (electrons.size() > 3 && jets.size() > 3) ? deltaR(electrons[3].eta, electrons[3].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Ele4Jet5_wh  :=  ? (electrons.size() > 3 && jets.size() > 4) ? deltaR(electrons[3].eta, electrons[3].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Ele4Jet6_wh  :=  ? (electrons.size() > 3 && jets.size() > 5) ? deltaR(electrons[3].eta, electrons[3].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Ele4Jet7_wh  :=  ? (electrons.size() > 3 && jets.size() > 6) ? deltaR(electrons[3].eta, electrons[3].phi, jets[6].eta, jets[6].phi) : -100 ",  
                           "dR_Ele5Jet1_wh  :=  ? (electrons.size() > 4 && jets.size() > 0) ? deltaR(electrons[4].eta, electrons[4].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele5Jet2_wh  :=  ? (electrons.size() > 4 && jets.size() > 1) ? deltaR(electrons[4].eta, electrons[4].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele5Jet3_wh  :=  ? (electrons.size() > 4 && jets.size() > 2) ? deltaR(electrons[4].eta, electrons[4].phi, jets[2].eta, jets[2].phi) : -100 ",
                           "dR_Ele5Jet4_wh  :=  ? (electrons.size() > 4 && jets.size() > 3) ? deltaR(electrons[4].eta, electrons[4].phi, jets[3].eta, jets[3].phi) : -100 ",
                           "dR_Ele5Jet5_wh  :=  ? (electrons.size() > 4 && jets.size() > 4) ? deltaR(electrons[4].eta, electrons[4].phi, jets[4].eta, jets[4].phi) : -100 ",
                           "dR_Ele5Jet6_wh  :=  ? (electrons.size() > 4 && jets.size() > 5) ? deltaR(electrons[4].eta, electrons[4].phi, jets[5].eta, jets[5].phi) : -100 ",
                           "dR_Ele5Jet7_wh  :=  ? (electrons.size() > 4 && jets.size() > 6) ? deltaR(electrons[4].eta, electrons[4].phi, jets[6].eta, jets[6].phi) : -100 ",                      
                           "dR_Pho1Jet3_wh :=  ? jets.size() > 2 ? deltaR(jets[2].eta, jets[2].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Jet3_wh :=  ? jets.size() > 2 ? deltaR(jets[2].eta, jets[2].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Jet4_wh :=  ? jets.size() > 3 ? deltaR(jets[3].eta, jets[3].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Jet4_wh :=  ? jets.size() > 3 ? deltaR(jets[3].eta, jets[3].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Jet5_wh :=  ? jets.size() > 4 ? deltaR(jets[4].eta, jets[4].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Jet5_wh :=  ? jets.size() > 4 ? deltaR(jets[4].eta, jets[4].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Jet6_wh :=  ? jets.size() > 5 ? deltaR(jets[5].eta, jets[5].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Jet6_wh :=  ? jets.size() > 5 ? deltaR(jets[5].eta, jets[5].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Jet7_wh :=  ? jets.size() > 6 ? deltaR(jets[6].eta, jets[6].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Jet7_wh :=  ? jets.size() > 6 ? deltaR(jets[6].eta, jets[6].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100"
]

dR_variables_VHLeptonicLoose = ["dR_Pho1Ele1_zh := ? electrons.size() > 0 ? deltaR(electrons[0].eta, electrons[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                                "dR_Pho1Ele2_zh := ? electrons.size() > 1 ? deltaR(electrons[1].eta, electrons[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                                "dR_Pho2Ele1_zh := ? electrons.size() > 0 ? deltaR(electrons[0].eta, electrons[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                                "dR_Pho1Ele2_zh := ? electrons.size() > 1 ? deltaR(electrons[1].eta, electrons[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                                "dR_Pho1Mu1_zh  := ? muons.size() > 0 ? deltaR(muons[0].eta, muons[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                                "dR_Pho1Mu2_zh  := ? muons.size() > 1 ? deltaR(muons[1].eta, muons[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                                "dR_Pho2Mu1_zh  := ? muons.size() > 0 ? deltaR(muons[0].eta, muons[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                                "dR_Pho2Mu2_zh  := ? muons.size() > 1 ? deltaR(muons[1].eta, muons[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100"
]

dR_variables_ZHLeptonic = ["dR_Pho1Jet1_loose :=  ? jets.size() > 0 ? deltaR(jets[0].eta, jets[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho1Jet2_loose :=  ? jets.size() > 1 ? deltaR(jets[1].eta, jets[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",  
                           "dR_Pho2Jet1_loose :=  ? jets.size() > 0 ? deltaR(jets[0].eta, jets[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho2Jet2_loose :=  ? jets.size() > 1 ? deltaR(jets[1].eta, jets[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Ele1_loose :=  ? electrons.size() > 0 ? deltaR(electrons[0].eta, electrons[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho1Ele2_loose :=  ? electrons.size() > 1 ? deltaR(electrons[1].eta, electrons[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",                           
                           "dR_Pho2Ele1_loose :=  ? electrons.size() > 0 ? deltaR(electrons[0].eta, electrons[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",                          
                           "dR_Pho2Ele2_loose :=  ? electrons.size() > 1 ? deltaR(electrons[1].eta, electrons[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho1Mu1_loose  :=  ? muons.size() > 0 ? deltaR(muons[0].eta, muons[0].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho1Mu2_loose  :=  ? muons.size() > 1 ? deltaR(muons[1].eta, muons[1].phi, diPhoton.leadingPhoton.eta, diPhoton.leadingPhoton.phi) : -100",
                           "dR_Pho2Mu1_loose  :=  ? muons.size() > 0 ? deltaR(muons[0].eta, muons[0].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Pho2Mu2_loose  :=  ? muons.size() > 1 ? deltaR(muons[1].eta, muons[1].phi, diPhoton.subLeadingPhoton.eta, diPhoton.subLeadingPhoton.phi) : -100",
                           "dR_Mu1Jet1_loose  :=  ? (muons.size() > 0 && jets.size() > 0) ? deltaR(muons[0].eta, muons[0].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu1Jet2_loose  :=  ? (muons.size() > 0 && jets.size() > 1) ? deltaR(muons[0].eta, muons[0].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Mu2Jet1_loose  :=  ? (muons.size() > 1 && jets.size() > 0) ? deltaR(muons[1].eta, muons[1].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Mu2Jet2_loose  :=  ? (muons.size() > 1 && jets.size() > 1) ? deltaR(muons[1].eta, muons[1].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele1Jet1_loose  :=  ? (electrons.size() > 0 && jets.size() > 0) ? deltaR(electrons[0].eta, electrons[0].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele1Jet2_loose  :=  ? (electrons.size() > 0 && jets.size() > 1) ? deltaR(electrons[0].eta, electrons[0].phi, jets[1].eta, jets[1].phi) : -100 ",
                           "dR_Ele2Jet1_loose  :=  ? (electrons.size() > 1 && jets.size() > 0) ? deltaR(electrons[1].eta, electrons[1].phi, jets[0].eta, jets[0].phi) : -100 ",
                           "dR_Ele2Jet2_loose  :=  ? (electrons.size() > 1 && jets.size() > 1) ? deltaR(electrons[1].eta, electrons[1].phi, jets[1].eta, jets[1].phi) : -100 "
]




WH_anomalous_dumper_variables = diphoton_variables + leptons_variables + dR_variables_WHLeptonic +jets_variables + custom_vars

